### ISSUE TITLE
Help related to backstage gitlab integration

### ISSUE THREAD

**Issue by rakeshreddyrg09** [vinaykv23/catalog-info#1]
Hi Vinay, I got your reference from [github issues]
I have few questions in terms of backstage integration with gitlab.
can you help me out.!

here is my configuration.

```yaml
integrations:
  gitlab:
    - host: code.org.com
      apiBaseUrl: https://code.org.com/api/v4
      token: ${GITLAB_TOKEN}
 ```
 ```yaml
catalog:
  providers:
    backstageOpenapi:
      plugins:
        - catalog
        - search
    gitlab:
      org:
        host: code.org.com
        orgEnabled: true
        group: backstage-org
        groupPattern: '[\s\S]*'
        schedule: 
          frequency: { minutes: 30 }
          timeout: { minutes: 3 } 
```
below is my pod logs
![image](https://github.com/user-attachments/assets/879e4076-0f9b-471d-a585-c72dabe882d0)

under kind: Group or kind: User
I'm not able to see any group or any users

can you guide please.
